resolver: lts-15.6

allow-newer: true

packages:
- 'alex-3.2.5'

apply-ghc-options: everything
ghc-options:
  "$everything": -split-sections -O2

system-ghc: true
extra-path:
  - /home/viluon/Projects/ghc-whole-program-compiler-project/ghc-wpc/_build/stage1/bin

# use custom ext-stg whole program compiler GHC
compiler:     ghc-8.11.0.20210324
# ghc-variant:  ext-stg-whole-program-compiler

setup-info-locations: []
setup-info:
  ghc:
    linux64-custom-ext-stg-whole-program-compiler:
      8.11.0.20200527:
        url: "https://github.com/grin-compiler/ghc-wpc/releases/download/ghc-8.11.0.20200527-wpc/ghc-8.11.0.20200527.tar.xz"
